### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> string $method ]] in class RoachPHP\Http\Request

### ISSUE THREAD

**Issue by Loukili-Rachid** [roach-php/laravel#8] opened 2022-02-09 14:13 UTC
Illuminate\Contracts\Container\BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> string $method ]] in class RoachPHP\Http\Request

i face this error when i just install a fresh Laravel project and roach-php / Laravel 
 
this is my code  
```
namespace App\Http\Controllers;

use RoachPHP\Http\Response;
use RoachPHP\Spider\BasicSpider;

class RoachDocsSpider extends BasicSpider
{
    /**
     * @var string[]
     */
    public array $startUrls = [
        'https://roach-php.dev/docs/spiders'
    ];
 
    public function parse(Response $response): \Generator
    {
        $title = $response->filter('h1')->text();

        $subtitle = $response
            ->filter('main > div:nth-child(2) p:first-of-type')
            ->text();

        yield $this->item([
            'title' => $title,
            'subtitle' => $subtitle,
        ]);
    }
}
```
i tried to install  also roach-php / core but the same error i follow the guide from doc, with initialRequests also, without succeed. 

environment : 
        "laravel/framework": "^8.75", 
        "nyholm/psr7": "^1.5",
        "roach-php/laravel": "^0.3.1"

**Comment by ksassnowski** [comment] 2022-02-09 14:15
Can you post the entire strack trace? It’s unclear when this error occurs

**Comment by Loukili-Rachid** [comment] 2022-02-23 13:48
@ksassnowski here we go brother
 

![2022-02-23_144802](https://user-images.githubusercontent.com/11983029/155332102-6863606a-60f7-4d3a-908d-7cfbc0a604cb.jpg)

![2022-02-23_144606](https://user-images.githubusercontent.com/11983029/155331928-4cee1587-1b5f-4fd7-b620-e6fe20072819.jpg)

**Comment by Loukili-Rachid** [comment] 2022-03-06 14:44
Hello everyone  is there any fix for this case i'm still stuck 
Thanks in advance any help is welcome

**Comment by ksassnowski** [comment] 2022-03-07 05:57
Can you maybe set up a small repository that reproduces this error? Because I still can't tell what is going wrong. There was a similar bug that occurred when you didn't publish the package config although that should have been fixed in 0.3.1

**Comment by Loukili-Rachid** [comment] 2022-03-12 12:40
hello @ksassnowski , sorry for late : here is an example : [](https://github.com/Loukili-Rachid/roach-app)

**Comment by ksassnowski** [comment] 2022-03-16 08:18
Ok, I see what's wrong. You're using your spider like a controller, which is not how you're supposed to do it. To start a spider, you call `Roach::startSpider(SpiderClass::class)`. See https://roach-php.dev/docs/spiders#running-spiders

**Closed by ksassnowski** 2022-03-16 08:18 UTC
